version: "3.8"
services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Frankfurt
      - AUTO_UPDATE=true #optional
    volumes:
      - jackett_config:/config
      - jackett_downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

volumes:
  jackett_config:
    driver: local
  jackett_downloads:
    driver: local
